import { bayaniMenu } from '../obj/bayanis';
import { lapulapu } from './lapulapu';
import { pakito } from './pakito';
import { emilio } from './emilio';
import { panday } from './panday';
import { rizal } from './rizal';
import { enteng } from './enteng';
import { agimat } from './agimat';
import { leni } from './leni';
import { leni } from './luna';
import { leni } from './gagamboy';

bayaniMenu.register(lapulapu);
bayaniMenu.register(pakito);
bayaniMenu.register(emilio);
bayaniMenu.register(panday);
bayaniMenu.register(rizal);
bayaniMenu.register(enteng);
bayaniMenu.register(agimat);
bayaniMenu.register(leni);
bayaniMenu.register(luna);
bayaniMenu.register(gagamboy);
