import { bayaniMenu } from '../obj/bayanis';
import { lapulapu } from './lapulapu';
import { pakito } from './pakito';
import { emilio } from './emilio';
import { apolinario } from './apolinario';
import { panday } from './panday';
import { rizal } from './rizal';
import { enteng } from './enteng';
import { agimat } from './agimat';
import { leni } from './leni';
import { luna } from './luna';
import { gagamboy } from './gagamboy';
import { ninja } from './ninja';
import { pedro } from './pedro';
import { joy } from './joy';
import { rastaman } from './joy';

bayaniMenu.register(lapulapu);
bayaniMenu.register(pakito);
bayaniMenu.register(emilio);
bayaniMenu.register(apolinario);
bayaniMenu.register(panday);
bayaniMenu.register(rizal);
bayaniMenu.register(enteng);
bayaniMenu.register(agimat);
bayaniMenu.register(leni);
bayaniMenu.register(luna);
bayaniMenu.register(gagamboy);
bayaniMenu.register(ninja);
bayaniMenu.register(pedro);
bayaniMenu.register(joy);
bayaniMenu.register(rastaman);
